# Generated by Django 5.1.1 on 2024-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='razao_social',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='empresa',
            name='contato_telefone',
            field=models.CharField(default='(00) 0000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
